s=dict({1:2,"hi":"hello",(7):(9),"sky":23})
print(s)
#print(dir(dict))
s.update({("Name","Surname"):"saurabh melgirkar"})
print(s)
print(s[1])
print(s[7])
print(s.get("Sky",21))
print(s)
print(s.keys())
print(s.values())
print(s.items())
s["Class"]="ty"
print(s.setdefault(11,5))
print(s)
s.pop(1)
print(s)
s.popitem()

print(s)